version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  test_expressjs_development:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --save
      - run:
          command: npm run jest
          name: run npm test

workflows:
  test_my_app:
    jobs:
      - test_expressjs_development
